language: elixir
elixir: '1.4.2'
otp_release: '19.3'
script: cd assets && npm install && node_modules/brunch/bin/brunch build && cd .. && mix test
services:
  - postgresql
  - redis-server
env:
  - REDIS_URL=redis://localhost:6379
cache:
  directories:
    - assets/node_modules
    - deps
    - _build
