language: ruby
bundler_args: --without development
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - "cp config/database.travis.yml config/database.yml"
script: ./script/cibuild.sh
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
