language: ruby
bundler_args: --without development
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - "cp config/database.travis.yml config/database.yml"
script: ./script/cibuild.sh
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: rbx-19mode
    - rvm: jruby-19mode
