version: '2'

# Quickstart:
#   docker-compose up -d web
#   docker-compose run --rm db_init

# To cleanup:
#   docker-compose stop && docker-compose rm

services:
  postgres:
    image: postgres
    container_name: asciinema_postgres

  redis:
    image: redis
    container_name: asciinema_redis

  sidekiq:
    image: asciinema/asciinema.org
    container_name: asciinema_worker
    links:
      - redis
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:mypass@postgres/asciinema"
      REDIS_URL: "redis://redis:6379"
      HOST: "localhost:3000"
    command: "ruby start_sidekiq.rb"
    volumes:
      - /tmp/asciinema/uploads:/app/uploads

  web:
    image: asciinema/asciinema.org
    container_name: asciinema_web
    links:
      - redis
      - postgres
    depends_on:
      - sidekiq
    environment:
      DATABASE_URL: "postgresql://postgres:mypass@postgres/asciinema"
      REDIS_URL: "redis://redis:6379"
      HOST: "localhost:3000" # replace with actual hostname/ip.... ${HOSTNAME} doesn't seem to work..
    ports:
      - "3000:80"
    volumes:
      - /tmp/asciinema/uploads:/app/uploads

  db_init:
    image: asciinema/asciinema.org
    links:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:mypass@postgres/asciinema"
    command: "bundle exec rake db:setup"
