version: '3'

volumes:
  bundle:
  m2:
  node_modules:
  build:
  deps:

services:
  postgres:
    image: postgres
    container_name: asciinema_dev_postgres

  redis:
    image: redis
    container_name: asciinema_dev_redis

  web:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    image: asciinema/asciinema-server:develop
    container_name: asciinema_dev_web
    entrypoint: env -u MIX_ENV -u RAILS_ENV
    command: /bin/bash
    links:
      - redis
      - postgres
    env_file: .env.development
    ports:
      - 3000:3000
      - 4000:4000
      - 4040:4040
    volumes:
      - ../uploads:/app/uploads:cached
      - bundle:/bundle:cached
      - node_modules:/app/assets/node_modules:cached
      - build:/app/_build:cached
      - deps:/app/deps:cached
      - m2:/root/.m2:cached
      - ../:/app:cached
      - /tmp/asciinema-web:/tmp
